### ISSUE TITLE
Switch project in SBT

### ISSUE THREAD

**Issue by unitymind** [storm-enroute/mecha#1]
It's expected behaviour? Can't switch to subproject in SBT. 

```
> projects
[info] In file:/Users/unitymind/developing/cleawing/examples/mecha-super-repo/
[info]   * super-storm-enroute
[info] In file:/Users/unitymind/developing/cleawing/examples/mecha-super-repo/examples-application/
[info]     examples-application
[info] In file:/Users/unitymind/developing/cleawing/examples/mecha-super-repo/examples-core-utils/
[info]     examples-core-utils
> project example-core-utils
[error] Not a valid project ID: examples-core-utils
[error] project examples-core-utils
[error]
```

**Comment by axel22** [comment]
This is a general consequence of declaring a dependency on a project defined in a completely different file.

The mecha super-project is automatically defined like this:

```
  val superproject = subprojects.foldLeft(Project(
    superName,
    superDirectory,
    settings = superSettings ++ Seq(
      mechaEditRefreshKey <<= mechaEditRefreshKey.dependsOn(refreshes: _*),
      mechaNightlyKey <<= mechaNightlyKey.dependsOn(nightlies: _*)
    )
  ))(_ aggregate _)
```

Here, subprojects are defined like this:

```
RootProject(uri(repo.dir))
```

In SBT, this means that subprojects cannot be referred to by their simple name. Instead, they have to be referred to by their full uri. So - there is a workaround:

```
project {file:/C:/cygwin/home/axel22/workspaces/scala/examples/mecha-super-repo/examples-core-utils}
```

A bit long, but - auto-complete to the rescue!
(I had no luck finding a workaround for this in SBT, but if I do, I can try to simplify it)

**Comment by unitymind** [comment]
Wow! Thanks for clarification. Just add your answer to README :)

**Comment by axel22** [comment]
Done!
