### ISSUE TITLE
The package cannot be found on maven central.

### ISSUE THREAD

**Issue by Raffaello** [storm-enroute/mecha#10]
Is there any other way to obtain the package?

I am not able to find it anywhere.

Could you please publish as a per documentation?

Thanks

**Comment by ghost** [comment]
The 0.3 version is here:

https://search.maven.org/artifact/com.storm-enroute/mecha/0.3/jar

**Comment by Raffaello** [comment]
> The 0.3 version is here:
> 
> https://search.maven.org/artifact/com.storm-enroute/mecha/0.3/jar

The `jar` is not found. if you click and try to download manually.

also in `sbt` is not resolved. 

https://search.maven.org/remotecontent?filepath=com/storm-enroute/mecha/0.3/mecha-0.3.jar

https://search.maven.org/remotecontent?filepath=com/storm-enroute/mecha/0.3/mecha-0.3.pom


Not sure. I might miss a step?

**Comment by ghost** [comment]
It's actually here: https://repo1.maven.org/maven2/com/storm-enroute/mecha_2.10_0.13/0.3/

It should be picked up automatically - for example, ScalaMeter is using it:

https://github.com/scalameter/scalameter/blob/master/project/plugins.sbt

**Comment by Raffaello** [comment]
ok it is something related to sbt/scala version then? I was trying to upgrade scalameter, modernizing the sbt version, migrating to 0.13 to 1.2.x and with the sbtplugin related. 

The only blocker that i am having actually is with mecha 0.3 not found,  when using sbt 1.2.8.

**Comment by ghost** [comment]
Maybe mecha needs to be recompiled and re-published for sbt 1.x?

To my knowledge, it was only used with pre-1.x sbt in the past, so mecha would need to be upgraded to Scala 2.12, and re-published for Scala 2.12.

**Comment by Raffaello** [comment]
yes probably and definitely i guessed the same. 
I have also started working on that but i need some help, I do not know how to extends from the `Build` trait that doesn't exist anymore and `Mecha` extends from that trait... .:/ Any suggestion about it?

Not sure if it is still required or sbt has integrated later some or partially other feature of mecha. I think it would not so an easy job..

**Comment by ghost** [comment]
I think that the `Mecha` trait should be replaced with an object that extends `AutoPlugin`.
Both pre-1.0 and post-1.0 sbt should work with it then, but the projects should no longer extend the `Mecha` trait - its keys would be mixed-in automatically. This would probably mean that the Mecha version would need to go up to 0.4.

https://www.scala-sbt.org/0.13/docs/Plugins.html

(I never did implemented an auto-plugin before, though, this is just my understanding)
