### ISSUE TITLE
Could not commit if message not one word

### ISSUE THREAD

**Issue by unitymind** [storm-enroute/mecha#3]
```
Commit message (empty aborts): Back to 0.3-SNAPSHOT
error: pathspec 'to' did not match any file(s) known to git.
error: pathspec '0.3-SNAPSHOT'' did not match any file(s) known to git.
[error] Could not commit.
```

If enter one word, e.g 'Back', without issue. Strange behaviour, because `Process(s"git commit -m '${msg}'", dir).! == 0` is simple and clear, but I can't assume where is command execution is broken ()

**Comment by axel22** [comment]
That is strange. Which platform are you using (OS, JDK, Scala version)?

**Comment by axel22** [comment]
On Windows, Cygwin, JDK 7 and SBT 0.13 thing seems to work well:

```
Commit message (empty aborts): Escape variables to guard against whitespaces.
[master d68f3b5] Escape variables to guard against whitespaces.
 2 files changed, 11 insertions(+), 11 deletions(-)
[success] Total time: 15 s, completed Jul 7, 2015 9:33:25 PM
```

**Comment by unitymind** [comment]
Mac OS X, Oracle JDK 1.8u45, sbt 0.13.7, Scala 2.11.7 (but sbt still using 2.10.x)

**Comment by axel22** [comment]
Sorry for the delay in getting back to you - I finally have some time now.
I can confirm the problem on Ubuntu.

It seems, ironically, that the commit message that I used in the example of the thing working in Cygwin,
and which I entered while solving a similar problem, is exactly the culprit.
Creating new processes via `Process(...).!!` in Unix systems is best done by passing a list of the command and command line arguments, instead of a string with the command and its arguments.

I will submit a fix soon.

**Comment by axel22** [comment]
Fixed in:

https://github.com/storm-enroute/mecha/commit/ccbbfcf9de85f08aad4adc13bb6b9a3177cb38b9

https://github.com/storm-enroute/mecha/commit/b309f63bbaeed81e173eb0f481ce17a8a51324ce

https://github.com/storm-enroute/mecha/commit/e6837f2215ed8c31f32e3933170ee9f70db1cedd

**Comment by axel22** [comment]
Thanks a lot for reporting, and sorry this went undetected before.

**Comment by unitymind** [comment]
Wow, thanks for your efforts. Already published as snapshot artifact?

**Comment by axel22** [comment]
That's a good question - they should normally be (https://ci.storm-enroute.com:8080).
I'll check it out soon.

On July 17, 2015 9:56:50 AM GMT+02:00, "Vitaliy V. Shopov" notifications@github.com wrote:

> Wow, thanks for your efforts. Already published as snapshot artifact?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/storm-enroute/mecha/issues/3#issuecomment-122209295

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by axel22** [comment]
[Should be published](https://ci.storm-enroute.com:8080/job/public-mecha/70/console), and changes in the snapshot (0.3-SNAPSHOT):

```
[info]  published mecha to https://oss.sonatype.org/content/repositories/snapshots/com/storm-enroute/mecha_2.10_0.13/0.3-SNAPSHOT/mecha-0.3-SNAPSHOT.jar
```

**Comment by unitymind** [comment]
Manually nuked plugin from ivy2 cache and new version resolved and works! Thank you

**Comment by axel22** [comment]
Awesome - thank you for reporting!

**Comment by unitymind** [comment]
Lol, this is core feature and don't work :) Really helpful to use one sbt console instead of additional bash terminals

**Comment by unitymind** [comment]
And we have new winner :)

```
> Exception in thread "Thread-32" java.io.IOException: Stream closed
    at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
    at java.io.OutputStream.write(OutputStream.java:116)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
    at scala.sys.process.BasicIO$$anonfun$input$1.apply(BasicIO.scala:191)
    at scala.sys.process.BasicIO$$anonfun$input$1.apply(BasicIO.scala:189)
    at scala.sys.process.ProcessBuilderImpl$Simple$$anonfun$2.apply$mcV$sp(ProcessBuilderImpl.scala:72)
    at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:22)
```

Basically after 20-30 or more seconds after mecha-push

**Comment by axel22** [comment]
Hey, didn't get the last comment - the `mecha-commit` feature still does not work on MacOSX?

**Comment by unitymind** [comment]
After update to latest snapshot - it works, as is mecha-commit, but seems not clearly close resource after external git execution

**Comment by axel22** [comment]
Interesting - I did not notice this on Cygwin and on Ubuntu.
Does it only happen after `mecha-commit`, or is it after you invoke `mecha-push`?

**Comment by unitymind** [comment]
Not sure, because `mecha-commit` and `mecha-push` - sequentially called :)

**Comment by axel22** [comment]
Would you mind doing another `mecha-commit` and waiting for a few minutes to see if the problem persists?

Then, if nothing happens for a while, could you call `mecha-push`?

I will have to get an access to a Mac to debug this.

**Comment by unitymind** [comment]
Could your suggest an article about how to develop and test sbt-plugins?  This can help me not only reporting, but make PR too :)

**Comment by unitymind** [comment]
Scenario to reproduce:
1. `mecha-push` with actually pushing new commit(s)
2. Just press Enter

`mecha-commit` not produce this issue.

**Comment by unitymind** [comment]
This is not crashing SBT, but annoying

**Comment by unitymind** [comment]
Clearly, `mecha-push` is cause

**Comment by axel22** [comment]
Awesome, thank you.

The easiest way is to publish the `mecha` plugin locally (or on Sonatype, but SBT's `publish-local` is faster). Then, another SBT project should depend on that local SBT artifact.

An even faster way is to make another project directly depend on the Mecha source tree.
I will try to write something soon, but the general idea is - instead of the sbt plugin as a library dependency in your project's project definition, you make the project depend on another local SBT project using the `dependsOn` combinator.

In [this file](https://github.com/storm-enroute/examples/blob/master/mecha-super-repo/project/plugins.sbt), instead of `addSbtPlugin`, you should have another `project/Build.scala` subfolder with something like this:

```
import java.io.File
import sbt._
import sbt.Keys._
object Plugins extends Build {
  val mechadir = new File(s"mecha")
  val mechaPlugin = {
    if (mechadir.exists) ProjectRef(file("../../mecha"), "mecha")
    else ProjectRef(uri("git://github.com/storm-enroute/mecha.git"), "mecha")
  }

  lazy val build = Project(
    "bundleboy-build",
    file(".")
  ).dependsOn(mechaPlugin)

  // boilerplate due to:
  // https://github.com/sbt/sbt/issues/895

  // Return our new resolver by default
  override def buildLoaders =
     BuildLoader.resolve(gitResolver) +: super.buildLoaders

  // Define a new build resolver to wrap the original git one
  def gitResolver(info: BuildLoader.ResolveInfo): Option[() => File] =
    if (info.uri.getScheme != "git")
      None
    else {
      // Use a subdirectory of the staging directory for the new plugin build.
      // The subdirectory name is derived from a hash of the URI,
      // and so identical URIs will resolve to the same directory.
      val hashDir = new File(info.staging,
          Hash.halfHashString(info.uri.normalize.toASCIIString))
      hashDir.mkdirs()

      // Return the original git resolver that will do the actual work.
      Resolvers.git(info)
    }
}
```

Taken from:

https://github.com/storm-enroute/bundleboy/blob/master/project/project/Build.scala

**Comment by axel22** [comment]
Ok, thanks for explaining - so you're saying it's `mecha-push`. I will check it out.

**Comment by axel22** [comment]
It is possible that invoking the `Process`'s `!<` method when pushing somehow caused the error you described on Mac OS X.

Now `mecha-push` uses `!` like the other commands, which could solve the Mac OS X problem:

https://github.com/storm-enroute/mecha/commit/6599f7af62aaf26a3bcb5a31808f7e633de06088

**Comment by unitymind** [comment]
Wow, great!
