### ISSUE TITLE
How often do you release a new version?

### ISSUE THREAD

**Issue by alibkord** [storm-enroute/mecha#5]
Hey folks, just wondering when the changes I submitted recently will be released so I can fetch it from sonatype instead of building locally. :-)

**Comment by axel22** [comment]
Hey, sorry for the delay - the 0.3 version was just released on Sonatype. Should appear here soonish (seems to be a bit non-responsive at the moment):

https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.storm-enroute%22%20AND%20a%3A%22mecha%22

http://central.maven.org/maven2/com/storm-enroute/mecha_2.10_0.13/

**Comment by alibkord** [comment]
Awesome, thanks.
