### ISSUE TITLE
Support for CrossProject (%%%) dependencies

### ISSUE THREAD

**Issue by viktor-podzigun** [storm-enroute/mecha#6]
First of all, thanks a lot for a very, very useful project!
For me it works great for both, from command line using `sbt` and inside the `IDE` (IntelliJ IDEA).

By now, the super-repo dependencies resolution are available only for Scala dependencies (`%%`).
But it would be nice to support `CrossProject` (`%%%`) dependencies as well, which are used by `Scala.js/Scala.native` projects.

Since I'm currently using mecha for `Scala.js` projects only, I've came up with the solution by copying and creating the local version of the method `MechaRepoBuild.superRepoDependencies` with the replaced `%%` by `%%%` for dependencies artifacts.

And I'm thinking about the generic solution right now.

**Comment by axel22** [comment]
Hi Viktor!

Glad to hear that you are finding this project useful! If you would like to contribute a patch that allows treating a dependency as both a JS and a JVM dependency, that is welcome!
